// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// auc_cpp
double auc_cpp(Rcpp::NumericVector group, Rcpp::NumericVector predictions);
RcppExport SEXP _netOP_auc_cpp(SEXP groupSEXP, SEXP predictionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type predictions(predictionsSEXP);
    rcpp_result_gen = Rcpp::wrap(auc_cpp(group, predictions));
    return rcpp_result_gen;
END_RCPP
}
// outer_add_cpp
Rcpp::NumericMatrix outer_add_cpp(Rcpp::NumericVector x, Rcpp::NumericVector y);
RcppExport SEXP _netOP_outer_add_cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(outer_add_cpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// procrustes_translated_cpp
Rcpp::List procrustes_translated_cpp(const Eigen::Map<Eigen::MatrixXd>& X, const Eigen::Map<Eigen::MatrixXd>& X_star);
RcppExport SEXP _netOP_procrustes_translated_cpp(SEXP XSEXP, SEXP X_starSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type X_star(X_starSEXP);
    rcpp_result_gen = Rcpp::wrap(procrustes_translated_cpp(X, X_star));
    return rcpp_result_gen;
END_RCPP
}
// connected_components_dense_cpp
Rcpp::List connected_components_dense_cpp(Rcpp::NumericMatrix A, bool include_self_loops);
RcppExport SEXP _netOP_connected_components_dense_cpp(SEXP ASEXP, SEXP include_self_loopsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< bool >::type include_self_loops(include_self_loopsSEXP);
    rcpp_result_gen = Rcpp::wrap(connected_components_dense_cpp(A, include_self_loops));
    return rcpp_result_gen;
END_RCPP
}
// connected_components_sparse_cpp
Rcpp::List connected_components_sparse_cpp(SEXP A, bool include_self_loops);
RcppExport SEXP _netOP_connected_components_sparse_cpp(SEXP ASEXP, SEXP include_self_loopsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type A(ASEXP);
    Rcpp::traits::input_parameter< bool >::type include_self_loops(include_self_loopsSEXP);
    rcpp_result_gen = Rcpp::wrap(connected_components_sparse_cpp(A, include_self_loops));
    return rcpp_result_gen;
END_RCPP
}
// shortest_path_distances_dense_cpp
Rcpp::NumericMatrix shortest_path_distances_dense_cpp(Rcpp::NumericMatrix A, bool directed, bool weighted, bool include_self_loops);
RcppExport SEXP _netOP_shortest_path_distances_dense_cpp(SEXP ASEXP, SEXP directedSEXP, SEXP weightedSEXP, SEXP include_self_loopsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< bool >::type directed(directedSEXP);
    Rcpp::traits::input_parameter< bool >::type weighted(weightedSEXP);
    Rcpp::traits::input_parameter< bool >::type include_self_loops(include_self_loopsSEXP);
    rcpp_result_gen = Rcpp::wrap(shortest_path_distances_dense_cpp(A, directed, weighted, include_self_loops));
    return rcpp_result_gen;
END_RCPP
}
// shortest_path_distances_sparse_cpp
Rcpp::NumericMatrix shortest_path_distances_sparse_cpp(SEXP A, bool directed, bool weighted, bool include_self_loops);
RcppExport SEXP _netOP_shortest_path_distances_sparse_cpp(SEXP ASEXP, SEXP directedSEXP, SEXP weightedSEXP, SEXP include_self_loopsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type A(ASEXP);
    Rcpp::traits::input_parameter< bool >::type directed(directedSEXP);
    Rcpp::traits::input_parameter< bool >::type weighted(weightedSEXP);
    Rcpp::traits::input_parameter< bool >::type include_self_loops(include_self_loopsSEXP);
    rcpp_result_gen = Rcpp::wrap(shortest_path_distances_sparse_cpp(A, directed, weighted, include_self_loops));
    return rcpp_result_gen;
END_RCPP
}
// lsm_pgd_cpp
Rcpp::List lsm_pgd_cpp(const Eigen::Map<Eigen::MatrixXd>& A_map, Eigen::MatrixXd Z, Eigen::VectorXd alpha, double step_size_Z, double step_size_alpha, int niter, bool trace);
RcppExport SEXP _netOP_lsm_pgd_cpp(SEXP A_mapSEXP, SEXP ZSEXP, SEXP alphaSEXP, SEXP step_size_ZSEXP, SEXP step_size_alphaSEXP, SEXP niterSEXP, SEXP traceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type A_map(A_mapSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type step_size_Z(step_size_ZSEXP);
    Rcpp::traits::input_parameter< double >::type step_size_alpha(step_size_alphaSEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    Rcpp::traits::input_parameter< bool >::type trace(traceSEXP);
    rcpp_result_gen = Rcpp::wrap(lsm_pgd_cpp(A_map, Z, alpha, step_size_Z, step_size_alpha, niter, trace));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_netOP_auc_cpp", (DL_FUNC) &_netOP_auc_cpp, 2},
    {"_netOP_outer_add_cpp", (DL_FUNC) &_netOP_outer_add_cpp, 2},
    {"_netOP_procrustes_translated_cpp", (DL_FUNC) &_netOP_procrustes_translated_cpp, 2},
    {"_netOP_connected_components_dense_cpp", (DL_FUNC) &_netOP_connected_components_dense_cpp, 2},
    {"_netOP_connected_components_sparse_cpp", (DL_FUNC) &_netOP_connected_components_sparse_cpp, 2},
    {"_netOP_shortest_path_distances_dense_cpp", (DL_FUNC) &_netOP_shortest_path_distances_dense_cpp, 4},
    {"_netOP_shortest_path_distances_sparse_cpp", (DL_FUNC) &_netOP_shortest_path_distances_sparse_cpp, 4},
    {"_netOP_lsm_pgd_cpp", (DL_FUNC) &_netOP_lsm_pgd_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_netOP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
