# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

auc_cpp <- function(group, predictions) {
    .Call(`_netOP_auc_cpp`, group, predictions)
}

outer_add_cpp <- function(x, y) {
    .Call(`_netOP_outer_add_cpp`, x, y)
}

procrustes_translated_cpp <- function(X, X_star) {
    .Call(`_netOP_procrustes_translated_cpp`, X, X_star)
}

connected_components_dense_cpp <- function(A, include_self_loops = FALSE) {
    .Call(`_netOP_connected_components_dense_cpp`, A, include_self_loops)
}

connected_components_sparse_cpp <- function(A, include_self_loops = FALSE) {
    .Call(`_netOP_connected_components_sparse_cpp`, A, include_self_loops)
}

shortest_path_distances_dense_cpp <- function(A, directed = FALSE, weighted = FALSE, include_self_loops = FALSE) {
    .Call(`_netOP_shortest_path_distances_dense_cpp`, A, directed, weighted, include_self_loops)
}

shortest_path_distances_sparse_cpp <- function(A, directed = FALSE, weighted = FALSE, include_self_loops = FALSE) {
    .Call(`_netOP_shortest_path_distances_sparse_cpp`, A, directed, weighted, include_self_loops)
}

lsm_pgd_cpp <- function(A_map, Z, alpha, step_size_Z, step_size_alpha, niter, trace = FALSE) {
    .Call(`_netOP_lsm_pgd_cpp`, A_map, Z, alpha, step_size_Z, step_size_alpha, niter, trace)
}

